version: '3'

services:

  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: client-docker-container
    networks:
      - loan-app-network
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: backend-docker-container
    networks:
      - loan-app-network
    volumes:
      - ./backend:/app

networks:
  loan-app-network:
